SELECT 
    LOCATION,
    LOCATION_ISO_CODE,
    MAX(NEW_RECOVERED) AS MAX_NEW_RECOVERED,
    MAX(TOTAL_RECOVERED) AS MAX_TOTAL_RECOVERED,
    MAX(NEW_ACTIVE_CASES) AS MAX_NEW_ACTIVE_CASES,
    MAX(TOTAL_ACTIVE_CASES) AS MAX_TOTAL_ACTIVE_CASES,
    MAX(NEW_DEATHS) AS MAX_NEW_DEATHS,
    MAX(TOTAL_DEATHS) AS MAX_TOTAL_DEATHS,
    MAX(TOTAL_CASES) AS MAX_TOTAL_CASES,
    MAX(GROWTH_FACTOR_OF_NEW_CASES) AS MAX_GROWTH_FACTOR_OF_NEW_CASES,
    MAX(TOTAL_DEATHS_PER_MILLION) AS MAX_TOTAL_DEATHS_PER_MILLION,
    MAX(GROWTH_FACTOR_OF_NEW_DEATHS) AS MAX_GROWTH_FACTOR_OF_NEW_DEATHS,
    MAX(NEW_CASES_PER_MILLION) AS MAX_NEW_CASES_PER_MILLION,
    MAX(NEW_DEATHS_PER_MILLION) AS MAX_NEW_DEATHS_PER_MILLION,
    MAX(CASE_RECOVERED_RATE) AS MAX_CASE_RECOVERED_RATE
FROM {{ source('database', 'COVID_DATA_BY_DATE') }}
GROUP BY 
    LOCATION,
    LOCATION_ISO_CODE
