SELECT 
    LOCATION,
    LOCATION_ISO_CODE,
    MIN(NEW_RECOVERED) AS MIN_NEW_RECOVERED,
    MIN(TOTAL_RECOVERED) AS MIN_TOTAL_RECOVERED,
    MIN(NEW_ACTIVE_CASES) AS MIN_NEW_ACTIVE_CASES,
    MIN(TOTAL_ACTIVE_CASES) AS MIN_TOTAL_ACTIVE_CASES,
    MIN(NEW_DEATHS) AS MIN_NEW_DEATHS,
    MIN(TOTAL_DEATHS) AS MIN_TOTAL_DEATHS,
    MIN(TOTAL_CASES) AS MIN_TOTAL_CASES,
    MIN(GROWTH_FACTOR_OF_NEW_CASES) AS MIN_GROWTH_FACTOR_OF_NEW_CASES,
    MIN(TOTAL_DEATHS_PER_MILLION) AS MIN_TOTAL_DEATHS_PER_MILLION,
    MIN(GROWTH_FACTOR_OF_NEW_DEATHS) AS MIN_GROWTH_FACTOR_OF_NEW_DEATHS,
    MIN(NEW_CASES_PER_MILLION) AS MIN_NEW_CASES_PER_MILLION,
    MIN(NEW_DEATHS_PER_MILLION) AS MIN_NEW_DEATHS_PER_MILLION,
    MIN(CASE_RECOVERED_RATE) AS MIN_CASE_RECOVERED_RATE
FROM {{ source('database', 'COVID_DATA_BY_DATE') }}
GROUP BY 
    LOCATION,
    LOCATION_ISO_CODE
